// A filled-in plan in the port's wording, as Multi-phase plan writes one, for
// testing check-plan.mjs through its command line. Tests break it one fault
// at a time with `replace`.

export const rule =
  "Tests alone are not sufficient verification. A PR is verified only when its unit, live, and perf boxes are all checked.";

const lanes = Array.from({ length: 10 }, (_, i) =>
  i === 0
    ? "- [ ] Lane 1. Regression lane against trunk. Run a retry against a dropped socket at trunk and head. Save `retry-drop.png`. Pass when both runs reconnect within five seconds."
    : `- [ ] Lane ${i + 1}. Retry case ${i + 1} on the staging server. Save \`retry-${i + 1}.png\`. Pass when the client reconnects once.`,
);

/** One PR section. `gated` gives it a review gate with boxes, otherwise `None.` */
export function prSection(title: string, id: string, depends: string, gated: boolean): string {
  return [
    `## ${title} (${id})`,
    "",
    `**Depends on.** ${depends}`,
    "",
    "**Files.**",
    "",
    "- [ ] Edit `src/net/retry.ts`.",
    "- [ ] Create `src/net/retry.test.ts`.",
    "",
    "**Build.**",
    "",
    "- [ ] Add `backoff` to `src/net/retry.ts`.",
    "",
    "**You see.**",
    "",
    "- [ ] The log prints `retry 1 after 200ms` on a dropped socket.",
    "",
    `**Verify, unit.** ${rule}`,
    "",
    "- [ ] `src/net/retry.test.ts` gains the backoff case. Run `bun test src/net/retry.test.ts`.",
    "",
    `**Verify, live.** ${rule} Ten lanes on the \`volume\` agent at the PR head, per the boot recipe.`,
    "",
    ...lanes,
    "",
    `**Verify, perf.** ${rule}`,
    "",
    "- [ ] Metric. Time to reconnect after a dropped socket, at trunk and head.",
    "- [ ] Probe. Drop the socket twenty times at trunk and at the head, interleaved.",
    "- [ ] Baseline. Record the trunk median first.",
    "- [ ] Rule. The head fails when its median is more than ten percent above trunk.",
    "",
    ...(gated
      ? [
          "**Review gate.** The operator reviews before merge.",
          "",
          `- [ ] Copy lane 2 screenshots into \`docs/media/${id}-review-retry.png\`.`,
          `- [ ] Record a 30 to 60 second video of the change on a lane worker. Save it as \`docs/media/${id}-review.mp4\`.`,
          "- [ ] Post the screenshots and the video in chat. Stop at merge-ready. Wait for the operator's click.",
        ]
      : [`**Review gate.** None. ${id} is not review-gated.`]),
    "",
    "**Merge.**",
    "",
    "- [ ] Root's clean verdict at the exact head SHA.",
    "- [ ] Review-bot triage done.",
    "- [ ] Rebased onto current trunk after the verdict, patch-id unchanged.",
    "- [ ] The root appends it to the base-branch stack and the operator lands it bottom-up.",
    "",
  ].join("\n");
}

export const samplePlan = [
  "# Network retry plan",
  "",
  "Dropped sockets reconnect with backoff instead of failing the request. Two PRs, R1 then R2.",
  "",
  "## How to read this",
  "",
  "One box is one unit of work. Every box names the evidence that checks it. A nested box is a sub-step of the box above it. Check a box only when its evidence exists, a file, a log line, a screenshot, a test run, or a SHA. The body is a how-to. The appendices explain and record.",
  "",
  "The program runs `${CLAUDE_PLUGIN_ROOT}/skills/poteto-mode/playbooks/autopilot-stack.md`. The operator lands the stack. R1 and R2 stop at merge-ready.",
  "",
  rule,
  "",
  "## Program checklist",
  "",
  "### Arm the program",
  "",
  "- [ ] Post this plan per the run's go. Start execution only on the go.",
  "- [ ] Read these at program start. Re-read them at every tick.",
  "  - [ ] `${CLAUDE_PLUGIN_ROOT}/skills/poteto-mode/playbooks/autopilot-stack.md`",
  "  - [ ] `${CLAUDE_PLUGIN_ROOT}/skills/swarm/SKILL.md`",
  "- [ ] On the go, arm the audit tick as `/loop 1h` with the tick prompt below.",
  "- [ ] Use this tick prompt, verbatim. \"Audit the operation and post a short status message to the operator only when something changed.\"",
  "",
  "### Spawn owners",
  "",
  "- [ ] Spawn one owner per PR with the full lifecycle the execution playbook names.",
  "",
  "### PR mechanics, for every PR",
  "",
  "- [ ] Open the PR with `gh pr create --base <base-branch>`.",
  "",
  "### Verdict and merge, for every PR",
  "",
  "- [ ] Clean only when every lane is `PASS`.",
  "",
  "### Boot recipe, for every live lane",
  "",
  "- [ ] `git fetch origin <head-branch> && git checkout <head SHA>`.",
  "",
  prSection("Add backoff to the retry loop", "R1", "None.", false),
  prSection("Show the retry state in the status bar", "R2", "R1.", true),
  "## Close the program",
  "",
  "- [ ] Every box above is checked with its evidence.",
  "",
  "## Appendix A. Prototype evidence",
  "",
  "None. No question needed a prototype.",
  "",
  "## Appendix B. Alternatives rejected",
  "",
  "A fixed delay lost to backoff under load.",
  "",
].join("\n");
